

service: serverless-hello-world

provider:
  name: aws
  runtime: nodejs10.x
  profile: David
  stage: dev
  region: us-west-2

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
